### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by vanniktech**
Deleted `about_terms_conditions` since it's not used. I'd recommend you to enable lint and fail it when there are warnings / errors

### CODE REVIEW

**Comment by medyo** [comment]
About Translation, I think we should do something more reusable, Many social networks share the same action name `follow`, `like`, `visit` ... Why not just translate these words and concat them with the appropriate social network name.

~~~xml
<!-- values/strings.xml -->
<string name="instagram">Instagram</string>
<string name="about_action_follow">Follow us on </string>

<!-- values-de/strings.xml -->
<string name="about_action_follow">Follow uns auf</string>
~~~

Then in code we could chain the action name with the right social network 

what do you think @vanniktech ?

**Comment by vanniktech** [comment]
I'd still prefer to have every string translated rather than trying to concatenate. This might work in 'simple' languages just as English / German but might not work for others (e.g. Chinese, Hebrew, Turkish etc).

**Comment by medyo** [comment]
Could you enlighten me about it. how it's not easy for other languages ? examples are welcome

I'm saying that, because maintenance is the key here, if for example, I'd like to add a new social network, I'll be forced to generate a string for each language whereas if we had some generic strings, we could easily add more elements.

**Comment by vanniktech** [comment]
I can't provide you any examples since I can only speak English and German and in those this would work. Like I said in other languages such as Chinese, Hebrew, Turkish this might not work.

**Comment by medyo** [comment]
I just asked a friend about the Korean translation and he confirmed that :  

~~~xml
<string name="about_action_follow">Follow us on Twitter</string>
~~~
Could be written like 
~~~xml
<string name="about_action_follow">Twitter 우리를 따르라</string>
~~~

I think we'll need a 3rd opinion

**Comment by greenaddress** [comment]
I think it is better to leave control of the words to translators and that trying to reuse here can cause more troubles down the line.

In some languages the slogan may be different across socials, the word ordering may be different or the 'sex' of the thing may change the word (for instance i think in Italian IL facebook is male while L'instagram is female) though with the set of current text it shouldn't be a problem yet. It can be especially problematic if a word has two meanings depending on context. 

It may make your life somewhat easier (?) but i think it's likely to make life more difficult for translators :(

**Pull request merged**
