### PR TITLE
Return Element in setOnClickListener(), for consistency's sake

### PR DESCRIPTION
**Pull request by geecko86**
All other setters do it

### CODE REVIEW

**Comment by geecko86** [comment]
Added a commit that corrects the Italian localization.

**Comment by vanniktech** [comment]
Oh nice this would also fix #58

**Comment by geecko86** [comment]
Yeah but don't hold your breath, this PR is 2 months old.

**Comment by vanniktech** [comment]
Yup seems like this library hasn't been maintained for the last 2 months.

**Comment by geecko86** [comment]
I use it in my app, so if needs be I'll end of forking it. cc @medyo

**Comment by medyo** [comment]
sorry for the delay guys, I've been busy !

**Pull request merged**
