### PR TITLE
Add setColor() method for element.

### PR DESCRIPTION
**Pull request by drogbababa**
So you can choose any color for your element.

### CODE REVIEW

**Comment by drogbababa** [comment]
two setBackgroundColor() method .One for elements, one for AboutPage.

**Comment by medyo** [comment]
@drogbababa could you make it support the Normal/Night mode ?

**Comment by drogbababa** [comment]
i read your demo,i think maybe this one has already supported Night mode.Because you can set any color you like for element or aboutPage in any mode. I mean maybe people want every element has different color or something, just set a Night mode is forcing people only to use dark color.

**Comment by medyo** [comment]
Yes, if you could add a new attribute to override those two attributes, that'd be great

**Comment by drogbababa** [comment]
so,you want me to write a setColor method which support Night/Normal color for all elements at once?

**Comment by medyo** [comment]
If that attribute is defined just ignore other colors (day, night)

**Comment by drogbababa** [comment]
i will have a try

**Pull request closed without merging**
